<?php

use Air\Crud\Model\Phrase;
use App\Helper\Route;

echo div(class: 'mt-50 ta-c', content: [
  h2(class: 'mb-10 fs-18', content: [
    span(class: 's-secondary', content: Phrase::t('Ой!!!')),
    Phrase::t('Ваш кошик порожній')
  ]),
  p(class: 'mb-30', content: Phrase::t('Перейдіть в наш магазин, подивіться різні категорії, вам точно що-небудь сподобатися')),
  a(href: Route::catalog(), class: 'btn-dark d-if ai-c gp-10', content: [
    Phrase::t('Перейти до каталогу'),
    faIcon('arrow-right', class: 'fs-10')
  ])
]);