<?php

use Air\Crud\Model\Phrase;
use App\Helper\Route;
use App\Module\Ui\View\Helper\Input;

echo $this->partial('auth/partial/container', ['form' => [

  $this->partial('auth/partial/header', [
    'title' => Phrase::t('Відновлення пароля'),
    'description' => Phrase::t('Введіть E-mail або телефон - ми спробуємо знайти ваш обліковий запис, потім відправимо тимчасовий пароль на вашу пошту.')
  ]),

  form(
    data: 'form-forgot-password',
    class: 'mt-30 p-20 d-b br-5 sc-level-1 fw-6 d-f jc-c gp-5',
    content: row(content: [
      col('col-12',
        Input::text(
          label: Phrase::t('E-mail або телефон'),
          description: Phrase::t('Якщо ви використовуєте телефон для входу - починайте введення з коду країни, наприклад "380..."'),
          name: 'login',
          error: Phrase::t('Ми не можемо знайти користувача з таким імейлом або телефоном')
        )
      ),
      col(
        class: 'col-7',
        content: flex(
          class: 'f-c gp-5 mt-20',
          content: [
            a(
              href: Route::auth(),
              class: 'td-u',
              content: Phrase::t('Згадали пароль?')
            ),
            a(
              href: Route::register(),
              class: 'td-u',
              content: Phrase::t('Ще немає облікового запису?')
            )
          ]
        )
      ),
      col('col-5 d-f jc-e', button(
        class: 'btn-primary fw-bold tt-u py-10 d-f jc-c gp-10 ai-c mt-20',
        isSubmit: true,
        content: [
          Phrase::t('Надіслати'),
          faIcon('chevron-right', class: 'fs-12')
        ]
      )),
      col('col-12', div(
        data: 'message',
        class: 'c-success mt-30 ta-c d-n',
        content: Phrase::t('Перевірте Email вказаний у вашому обліковому записі - ми на нього надіслали тимчасовий пароль.')
      )),
    ])
  )
]]);