<?php

use Air\Crud\Model\Phrase;
use App\Helper\Route;
use App\Model\ShopSettings;
use App\Module\Ui\View\Helper\Input;

$shopSettings = ShopSettings::singleOne();

echo $this->partial('auth/partial/container', ['form' => [

  $this->partial('auth/partial/header', [
    'title' => Phrase::t('Реєстрація'),
    'description' => Phrase::t('На вказаний E-mail прийде лист із посиланням для активації облікового запису')
  ]),

  $this->partial('auth/partial/oauth', [
    'title' => Phrase::t('Зареєструватися за допомогою Google')
  ]),

  form(
    data: 'form-register',
    class: 'mt-30 p-20 d-b br-5 sc-level-1 fw-6 d-f jc-c gp-5',
    content: row(content: [
      col('col-12',
        Input::text(
          label: Phrase::t('Ім\'я'),
          name: 'firstName',
          error: Phrase::t('Перевірте введене ім\'я'),
        )
      ),
      col('col-12',
        Input::text(
          label: Phrase::t('Прізвище'),
          name: 'secondName',
          error: Phrase::t('Перевірте введене прізвище')
        )
      ),
      col('col-12',
        Input::text(
          label: Phrase::t('Телефон'),
          name: 'phone',
          error: Phrase::t('Перевірте введений телефон, або він уже зареєстрований'),
          inputAttributes: $shopSettings->phoneMaskEnabled && strlen($shopSettings->phoneMask)
            ? ['data-input-mask' => "+38 000 000 00 00"]
            : null
        )
      ),
      col('col-12',
        Input::text(
          label: Phrase::t('E-mail'),
          name: 'email',
          error: Phrase::t('Перевірте введений E-mail, або він уже зареєстрований')
        )
      ),
      col('col-12 mt-20',
        Input::text(
          label: Phrase::t('Пароль'),
          name: 'password',
          error: Phrase::t('Пароль не є безпечним')
        )
      ),
      col(
        class: 'col-7',
        content: a(
          href: Route::auth(),
          class: 'td-u d-b mt-20 py-10',
          content: Phrase::t('Вже є аккаунт?')
        )
      ),
      col('col-5 d-f jc-e', button(
        class: 'btn-primary fw-bold tt-u py-10 d-f jc-c gp-10 ai-c mt-20',
        isSubmit: true,
        content: [
          Phrase::t('Зареєструватись'),
          faIcon('chevron-right', class: 'fs-12')
        ]
      )),
      col('col-12', div(
        data: 'message',
        class: 'c-success mt-30 ta-c d-n',
        content: Phrase::t('Перевірте вказаний Email – ми на нього відправили посилання для активації облікового запису.')
      )),
    ])
  )
]]);