<?php

use Air\Crud\Model\Phrase;
use Air\Type\FaIcon;
use Air\View\View;
use App\Helper\Route;
use App\Model\Category;
use App\Model\General;

/** @var View $this */

$general = General::singleOne();
$categories = Category::singleAll(['parent' => null], count: 7);

echo footer(
  class: 'sc-level-1 py-40',
  content: container(
    content: row(content: [
      col(
        class: 'col-12 col-sm-6 col-lg-3 mb-20 mb-lg-0',
        content: flex(
          class: 'gp-20 f-c',
          content: [
            a(href: Route::home(), class: 'mb-10', content: [
              img(src: 'images/logo-light.png', class: 'h-26 h-md-40'),
            ]),
            div(class: 'o-80', content: $general->title),
            div(class: 'o-80', content: $general->address),
            flex(class: 'ai-c gp-10', content: [
              a(
                class: 'fs-30 c-primary',
                href: Route::tel($general->phones['0']),
                data: ['title' => Phrase::t('Подзвонити нам')],
                content: faIcon(icon: 'phone-volume', style: FaIcon::STYLE_DUOTONE)
              ),
              flex(class: 'f-c sticky-hide', content: [
                a(class: 'r', content: Phrase::t('Написати нам')),
                a(class: 'r fw-6 fs-16 ls-m08', href: Route::tel($general->phones[0]), content: $general->phones[0]),

              ])
            ]),
            $this->partialCached('component/layout/partial/socials'),
          ]
        )
      ),
      col(class: 'col-12 col-sm-6 col-lg-3 mb-20 mb-lg-0', content: [
        div(class: 'fs-16 fw-bold px-10', content: Phrase::t('Головне Меню')),
        flex(class: 'f-c gp-10 mt-10 sticky-menu', content: $this->partialCached('component/layout/partial/menu')),
      ]),
      col(class: 'col-sm-6 col-lg-3 mb-20 mb-lg-0', content: [
        div(class: 'fs-16 fw-bold px-10', content: Phrase::t('Категорії товарів')),
        flex(class: 'f-c gp-10 mt-10 sticky-menu', content: function () use ($categories) {
          foreach ($categories as $category) {
            echo a(href: Route::catalog(category: $category), content: [faIcon(icon: $category->faIcon), $category->title]);
          }
          echo a(href: Route::catalog(), content: [faIcon(icon: 'list'), Phrase::t('Перегляд категорій')]);
        })
      ]),
      col(class: 'col-12 col-sm-6 col-lg-3', content: [
        div(class: 'fs-16 fw-bold px-10', content: Phrase::t('Куточок покупця')),
        flex(class: 'f-c gp-10 mt-10 sticky-menu', content: [
          a(class: 'fw-6', content: [faIcon('badge-check'), Phrase::t('Гарантія')]),
          a(class: 'fw-6', content: [faIcon('scale-balanced'), Phrase::t('Правила користування сайтом')]),
          a(class: 'fw-6', content: [faIcon('arrows-rotate'), Phrase::t('Обмін і повернення товару')]),
          a(class: 'fw-6', content: [faIcon('shield-check'), Phrase::t('Політика конфіденційності')]),
        ])
      ]),
    ])
  )
);

echo div(
  class: 'sc-level-2 py-20',
  content: container(
    row(class: 'ai-c', content: [
      col(class: 'col-12 col-md-6 ta-c ta-md-l r mb-10', content: $general->copyright),
      col(class: 'col-12 col-md-6 ta-c ta-md-r mt-10 mt-md-0', content: [
        div(class: 'mb-10 r', content: Phrase::t('Ми використовуємо безпечну оплату')),
        img(src: 'images/payment.png')
      ]),
    ])
  )
);
