<?php

use Air\Type\File;
use Air\Type\RichContent;

/** @var string $title */
$title = $this->title;

/** @var RichContent[] $richContent */
$richContent = $this->richContent;

echo container(
  class: 'my-20',
  content: [
    $this->partial('component/header', ['breadcrumbs' => $title]),
    richContent(
      content: $richContent,
      containerClassName: 'd-f f-c gp-30',

      /** @var File[] $files */
      filesRenderer: function (array $files) {
        return $this->partial('component/gallery', [
          'images' => $files
        ]);
      },
      fileRenderer: function (File $file) {
        if ($file->isImage()) {
          return img(src: $file, class: 'w-f br-4 of-con');
        }
        return video(src: $file, class: 'w-f br-4', attributes: ['controls']);
      },
      textRenderer: function (string $text) {
        return div(class: 'd-f f-c gp-20', content: nl2br($text));
      },
      htmlRenderer: function (string $html) {
        return div(class: 'd-f f-c gp-20', content: $html);
      },
      embedRenderer: function (string $embed) {
        return iframe($embed, class: 'br-4 of-h ar-16-9 w-f', attributes: ['allowfullscreen']);
      },
    )
  ]
);