<?php

use Air\Crud\Model\Phrase;
use App\Model\Order;

/** @var Order $order */
$order = $this->order;

if ($order->status === Order::PAYMENT_STATUS_SUCCESS) {
  echo div(
    class: 'bw-3 br-4 bc-success sc-success p-20 fw-bold fs-20 d-f ai-c jc-c gp-10',
    content: Phrase::t('Дякую. Ваше замовлення було отримано')
  );
  return;
}

echo div(
  class: 'bw-3 br-4 bc-warning sc-warning p-20 fw-bold fs-18 d-f ai-s jc-c gp-10',
  content: Phrase::t('Упс... Оплата замовлення не пройшла успішно. Будь ласка, спробуйте знову або зв\'яжіться з банком.')
);