<?php

use App\Model\Order;

/** @var Order $order */
$order = $this->order;
?>

<div class="p-3 position-sticky top-0 z-i-1001 header">
  <div class="card position-sticky w-100">
    <div class="card-body p-3 d-flex justify-content-between align-items-center">
      <h5 class="m-0 p-0">
        <i class="fas fa-info-circle me-1"></i>
        Офіс / Замовлення # <?php echo $order->number; ?>
      </h5>
      <div class="d-flex align-items-center">
        <a href="javascript: nav.back();" class="btn btn-primary ms-2 px-3"
           data-mdb-ripple-init>
          <i class="fa fa-arrow-left me-1"></i>
          Назад
        </a>
      </div>
    </div>
  </div>
</div>

<div class="p-3 pt-0 overflow-hidden overflow-y-auto z-1 content">
  <div class="row">
    <div class="col-5">
      <?php echo $this->partial('order/partial/contacts'); ?>
      <div class="mt-3">
        <?php echo $this->partial('order/partial/delivery'); ?>
      </div>
      <div class="mt-3">
        <?php echo $this->partial('order/partial/payment'); ?>
      </div>
    </div>
    <div class="col-7">
      <?php echo $this->partial('order/partial/cart'); ?>
    </div>
  </div>
</div>