<?php

use Air\View\View;

/** @var View $this */

echo container(
  class: 'py-30',
  content: row(
    class: 'gt-20 gty-lg-50 gtx-lg-100 pt-2',
    content: [
      col(class: 'col-12 col-lg-8', content: $this->partial('product/partial/content-and-specifications')),
      col(
        class: 'col-12 col-lg-4 pt-0 pt-lg-40',
        content: div(class: 'p-sk t-80', content: $this->partial('component/adv/vertical'))
      )
    ]
  )
);