<script>
  // let theme = localStorage.getItem("theme");
  // if (!theme) {
  //   theme = (window.matchMedia && window.matchMedia("(prefers-color-scheme: dark)").matches) ? "dark" : "light";
  // }
  // const html = document.querySelector("html");
  // html.setAttribute('data-bs-theme', theme);

  const switchTheme = () => {
    const html = document.querySelector("html");
    if (html.getAttribute('data-bs-theme') === 'dark') {
      html.setAttribute('data-bs-theme', 'light');
      localStorage.setItem('theme', 'light')
    } else {
      html.setAttribute('data-bs-theme', 'dark');
      localStorage.setItem('theme', 'dark')
    }
  };
</script>