<?php

use App\Model\Coupon;
use App\Model\Order;

/** @var Order $order */
$order = $this->order;
?>

<div class="card">
  <div class="card-body p-3">
    <div class="row">
      <div class="col-6">
        <h6 class="p-0 m-0 lead">
          <i class="fas fa-shopping-cart me-1"></i>
          Кошик
        </h6>
      </div>
      <div class="col-6 text-end">
        <span class="badge badge-primary">
          Кількість: <?php echo $order->count; ?> шт
        </span>
      </div>
    </div>
    <hr>
    <div class="row gy-3">
      <div class="col-4 fw-bold">
        Товар
      </div>
      <div class="col-4 text-end">
        Кількість
      </div>
      <div class="col-2 text-end">
        Ціна
      </div>
      <div class="col-2 text-end">
        Сума
      </div>
      <?php foreach ($order->products as $item) : ?>

        <div class="col-6 fw-bold">
          <div class="d-flex align-items-start">

            <img style="width: 50px; height: 50px; margin-top: 5px;"
                 class="object-fit-cover"
                 src="<?php echo $item->getProduct()->image->getSrc(); ?>">

            <div class="ms-3">
              <strong class="d-block text-color-dark line-height-1 font-weight-semibold">
                <?php echo $item->getProduct()->title; ?>
              </strong>
              <div class="text-2 text-primary">
                <?php echo $item->getProduct()->category->title; ?>
              </div>
            </div>
          </div>
        </div>
        <div class="col-2 text-end">
          <span class="badge badge-light">
            <?php echo $item->getCount(); ?> шт
          </span>
        </div>
        <div class="col-2 text-end">
          <span class="badge badge-light">
            <?php echo $item->getProduct()->price; ?> грн
          </span>
        </div>
        <div class="col-2 text-end">
          <span class="badge badge-light">
            <?php echo $item->getCount() * $item->getProduct()->price; ?> грн
          </span>
        </div>
      <?php endforeach; ?>
    </div>

    <?php if ($order->coupon && $order->coupon->type !== Coupon::TYPE_INFO) : ?>
      <hr>
      <div class="row">
        <div class="col-6 text-color-dark text-4 fw-bold">
          Вартість замовлення
        </div>
        <div class="col-6 text-end">
          <span class="badge badge-light">
            <?php echo $order->priceWithoutDiscount; ?> грн
          </span>
        </div>
      </div>
      <div class="row mt-2">
        <div class="col-6 text-color-dark text-4">
          <span class="fw-bold">Знижка купона</span>
          <span class="badge badge-primary">
            <?php echo $order->coupon->code; ?>
          </span>
        </div>
        <div class="col-6 text-end">
          <span class="badge badge-light">
            <?php echo match ($order->coupon->type) {
              Coupon::TYPE_FIXED => $order->coupon->value . ' грн',
              Coupon::TYPE_PERCENTAGE => $order->coupon->value . ' %',
            }; ?>
          </span>
        </div>
      </div>

    <?php elseif ($order->coupon && $order->coupon->type === Coupon::TYPE_INFO) : ?>
      <hr>
      <div class="row">
        <div class="col-6 text-color-dark text-4">
          <span class="fw-bold">Купон</span>
          <span class="badge badge-primary"><?php echo $order->coupon->code; ?></span>
        </div>
        <div class="col-6 text-end">
          <span class="badge badge-info">
            Інформаційний
          </span>
        </div>
      </div>
    <?php endif; ?>
    <hr>
    <div class="row">
      <div class="col-6 fs-4 fw-bold">
        Підсумкова вартість замовлення
      </div>
      <div class="col-6 fw-bold fs-4 text-end">
        <?php echo $order->price; ?> грн
      </div>
    </div>
  </div>
</div>