<?php

use App\Model\Order;

/** @var Order $order */
$order = $this->order;
?>
<div class="card">
  <div class="card-body p-3">
    <div class="row">
      <div class="col-4">
        <h6 class="p-0 m-0 lead">
          <i class="fas fa-truck me-1"></i>
          Доставка
        </h6>
      </div>
      <div class="col-8 text-end">
        <span class="badge badge-primary">
          <?php echo match ($order->deliveryMethod) {
            Order::DELIVERY_NEW_POST_DOOR => 'Доставка до будинку Новою Поштою',
            Order::DELIVERY_NEW_POST_WAREHOUSE => 'Забрати зі складу Новою Поштою',
            Order::DELIVERY_DOOR => 'Доставка до дому',
            Order::DELIVERY_WAREHOUSE => 'Самовивіз зі складу',
          }; ?>
        </span>
      </div>
    </div>
    <?php if (in_array($order->deliveryMethod, [Order::DELIVERY_DOOR, Order::DELIVERY_WAREHOUSE]) && count($order->address)) : ?>
      <hr class="mt-3">
      <?php foreach ($order->address as $key => $value) : ?>
        <div class="row mt-3">
          <div class="col-4"><?php echo ucfirst($key); ?></div>
          <div class="col-8 text-info text-end"><?php echo $value; ?></div>
        </div>
      <?php endforeach; ?>
    <?php endif; ?>
  </div>
</div>