<?php

use Air\Crud\Model\Phrase;
use Air\Type\FaIcon;
use Air\View\View;
use App\Module\Ui\View\Helper\Input;
use App\Service\User\Auth;

/** @var View $this */

$user = Auth::getUser();

echo $this->partial('profile/partial/preview', [
  'icon' => faIcon(icon: FaIcon::ICON_ENVELOPE),
  'title' => Phrase::t('Зміна електронної пошти'),
  'inner' => form(
    data: 'form-change-email',
    class: 'd-b br-5 sc-level-1 fw-6 d-f jc-c gp-5',
    content: row(
      class: 'gt-10',
      content: [
        col('col-12', [
          div(class: 'c-gray fs-14 mb-5', content: Phrase::t('Ваш поточний емейл') . ': '),
          div(class: 'mb-20 c-secondary', content: $user->email),
          div(class: 'c-gray fs-14', content: Phrase::t('На новий емейл прийде посилання для підтвердження')),
        ]),
        col('col-12',
          Input::text(
            label: Phrase::t('Введіть новий емейл'),
            name: 'email',
            error: Phrase::t('Перевірте введений E-mail, або він уже зареєстрований')
          )
        ),
        col('col-12 d-f jc-e', button(
          class: 'btn-primary fw-bold tt-u py-10 d-f jc-c gp-10 ai-c mt-20',
          isSubmit: true,
          content: [
            Phrase::t('Надіслати'),
            faIcon('chevron-right', class: 'fs-12')
          ]
        )),
      ])
  ),
]);