<?php

use Air\Crud\Model\Phrase;
use Air\Type\FaIcon;
use Air\View\View;
use App\Module\Ui\View\Helper\Input;

/** @var View $this */

echo $this->partial('profile/partial/preview', [
  'icon' => faIcon(icon: FaIcon::ICON_LOCK),
  'title' => Phrase::t('Зміна паролю'),
  'inner' => form(
    data: 'form-change-password',
    class: 'd-b br-5 sc-level-1 fw-6 d-f jc-c gp-5',
    content: row(
      class: 'gt-10',
      content: [
        col('col-12',
          Input::password(
            label: Phrase::t('Введіть поточный пароль'),
            name: 'currentPassword',
            error: Phrase::t('Перевірте введений пароль')
          )
        ),
        col('col-12',
          Input::password(
            label: Phrase::t('Введіть новий пароль'),
            name: 'newPassword',
            error: Phrase::t('Перевірте введений пароль')
          )
        ),
        col('col-12 d-f jc-e', button(
          class: 'btn-primary fw-bold tt-u py-10 d-f jc-c gp-10 ai-c mt-20',
          isSubmit: true,
          content: [
            Phrase::t('Змінити'),
            faIcon('chevron-right', class: 'fs-12')
          ]
        )),
      ])
  ),
]);