<?php

use Air\Crud\Model\Phrase;
use Air\Type\FaIcon;
use Air\View\View;
use App\Model\ShopSettings;
use App\Module\Ui\View\Helper\Input;
use App\Service\User\Auth;

/** @var View $this */

$user = Auth::getUser();
$shopSettings = ShopSettings::singleOne();

echo $this->partial('profile/partial/preview', [
  'icon' => faIcon(icon: FaIcon::ICON_USER),
  'title' => Phrase::t('Мої дані'),
  'inner' => form(
    data: 'form-personal-data',
    class: 'd-b br-5 sc-level-1 fw-6 d-f jc-c gp-5',
    content: row(
      class: 'gt-10',
      content: [
        col('col-12',
          Input::text(
            label: Phrase::t('Ім\'я'),
            name: 'firstName',
            value: $user->firstName,
            error: Phrase::t('Перевірте введене ім\'я'),
          )
        ),
        col('col-12',
          Input::text(
            label: Phrase::t('Прізвище'),
            name: 'secondName',
            value: $user->secondName,
            error: Phrase::t('Перевірте введене прізвище')
          )
        ),
        col('col-12',
          Input::text(
            label: Phrase::t('Телефон'),
            name: 'phone',
            value: $user->phone,
            error: Phrase::t('Перевірте введений телефон, або він уже зареєстрований'),
            inputAttributes: $shopSettings->phoneMaskEnabled && strlen($shopSettings->phoneMask)
              ? ['data-input-mask' => "+38 000 000 00 00"]
              : null
          )
        ),
        col('col-12 d-f jc-e', button(
          class: 'btn-primary fw-bold tt-u py-10 d-f jc-c gp-10 ai-c mt-20',
          isSubmit: true,
          content: [
            Phrase::t('Зберегти'),
            faIcon('chevron-right', class: 'fs-12')
          ]
        )),
      ])
  ),
]);