<?php

use Air\Cache;
use Air\View\View;
use App\Helper\Route;
use App\Model\Product;

/** @var View $this */

/** @var array $filters */
$filters = $this->category?->filters ?? $this->catalogSettings?->filters ?? [];

/** @var Product[] $products */
$products = $this->products;

/** @var string $search */
$search = $this->search;

echo Cache::quick([Route::currentRouteId(), 'catalog', 'heading'], function () {
  echo container(class: 'my-14', content: $this->partial('catalog/partial/breadcrumbs'));
  echo container(class: 'mb-14', content: $this->partial('catalog/partial/banners'));
});

echo container(
  form(
    action: Route::catalog(),
    data: 'catalog-form',
    content: row([
      col(class: 'col-12 col-lg-3 col-md-4 mb-md-30 mb-0', content: $this->partial('catalog/partial/aside')),
      col(class: 'col-lg-9 col-md-8', content: function () use ($products, $search) {

        if ($search) {
          echo hidden('search', $search);
        }

        echo $this->partial('catalog/partial/sorting');
        echo $this->partial('catalog/partial/selected-filters');

        echo Cache::quick([Route::currentRouteId(), 'catalog', 'products'], function () use ($products) {
          if (count($products)) {
            echo row(class: 'gt-10 gt-sm-20', content: function () use ($products) {
              foreach ($products as $product) {
                echo col(
                  class: 'col-6 col-sm-6 col-lg-4 col-xl-3',
                  content: $this->partial('component/product/preview/default', [
                    'product' => $product
                  ]));
              }
            });
          } else {
            echo $this->partial('catalog/partial/no-products');
          }
          echo $this->partial('catalog/partial/paging');
        });
      }),
    ])));