<?php

use Air\Crud\Model\Phrase;
use Air\Type\FaIcon;
use Air\View\View;
use App\Helper\Route;
use App\Module\Ui\View\Helper\Input;
use App\Service\User\Auth;

/** @var View $this */

$user = Auth::getUser();

echo $this->partial('profile/partial/preview', [
  'icon' => faIcon(icon: FaIcon::ICON_MAP),
  'title' => Phrase::t('Мої адреси'),
  'link' => [
    'title' => Phrase::t('Додати адресу'),
    'url' => Route::profileAddresses()
  ],
  'inner' => div(content: function () use ($user) {
    $addresses = ($user->addresses ?? []);

    if (!count(($user->addresses ?? []))) {
      echo div(class: 'o-80', content: Phrase::t('Ви поки що не додали жодної адреси'));
      return;
    }

    echo flex(class: 'f-c gp-10', content: function () use ($addresses) {
      foreach ($addresses as $index => $address) {
        echo flex(content: [
          a(
            class: 'fw-4 td-u',
            href: Route::profileAddresses($index),
            content: implode(', ', $address->toArray())
          ),
          Input::pillIcon(
            class: 'flex-s-0 ml-20',
            icon: FaIcon::ICON_CLOSE,
            style: 'danger',
            title: Phrase::t('Видалити адресу?'),
            data: ['remove-address' => $index]
          )
        ]);
      }
    });
  })
]);