<?php

use Air\Crud\Model\Phrase;
use App\Helper\Route;

echo div(class: 'mt-10 ta-c', content: [
  h2(class: 'mb-10 fs-18', content: [
    span(class: 'c-secondary', content: Phrase::t('Ой!!!')),
    ' ',
    Phrase::t('За заданими параметрами немає товарів')
  ]),
  p(class: 'mb-15', content: Phrase::t('Спробуйте погратися з фільтрами або перейдіть на головну сторінку каталогу')),
  a(href: Route::catalog(), class: 'btn-dark d-if ai-c gp-10', content: [
    Phrase::t('Перейти до каталогу'),
    faIcon('arrow-right', class: 'fs-10')
  ])
]);