<?php

use Air\Crud\Model\Language;
use Air\Crud\Model\Phrase;
use Air\View\View;
use App\Helper\Route;

/** @var View $this */

$languages = Language::all();

echo flex(class: 'f-c h-f', content: [
  a(href: Route::home(), class: 'mb-10', content: [
    img(src: 'images/logo-light.png', class: 'h-26 h-md-40'),
  ]),
  div(
    class: 'flex-g-1',
    content: swiperStatic(
      dataId: 'mobile-menu',
      slides: [
        [
          div(class: 'mobile-menu', content: [
            $this->partialCached('component/layout/partial/menu'),
//            a(data: ['badge' => 23], content: [
//              faIcon(icon: 'heart', class: 'icon'),
//              Phrase::t('Вибране')
//            ])
          ]),
          a(href: Route::catalog(), class: 'd-f mt-20 ai-c', data: ['force' => true, 'mobile-category-btn'], content: [
            $this->partial('component/layout/partial/catalog-logo'),
            span(class: 'flex-g-1 fw-bold tt-u ml-10', content: Phrase::t('Перегляд категорій')),
            div(class: 'w-50 h-30 d-f ai-c jc-e', content: faIcon(icon: 'chevron-up', class: 'rot-90'))
          ])
        ],
        div(class: 'mobile-categories', data: ['mobile-category-container'])
      ]
    )),
  div(class: 'pt-30 pb-15', content: [
    $this->partialCached('component/layout/partial/socials'),
    div(class: 'sc-level-3 h-1 mt-10'),
    div(class: 'mt-10', content: Phrase::t('Ми використовуємо безпечну оплату')),
    img(src: 'images/payment.png', class: 'mt-10')
  ])
]);